# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38316a7b54ae7797ee45c188764ea35377c0678eb8528c9e05da4b789c93649b424c7ef6c02971e5bec0acf46b92bdc10848840e96a2f5bb231b268fb6a0a966

test:
  secret_key_base: f85ed47215282ef44e3c5590441bdaf19748ef12b567c84b6afe2f6b1de1576e6e42160aed37940db7db7318d2f2d1d24d50728a64fe994e3991727ff6d8bddf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
